# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rack-noie6"
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jerod Santo", "Julio Cesar Ody", "Will Jessop"]
  s.date = "2011-12-10"
  s.email = "jerod.santo@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "VERSION.yml",
    "lib/noie6.rb",
    "rack-noie6.gemspec",
    "test/noie6_test.rb"
  ]
  s.homepage = "http://github.com/sant0sk1/rack-noie6"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A Rack middleware to redirect IE6 users out of your website"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

